# Configuration for VSCode/Cursor markdownlint extension (matches CodeRabbit AI linter)
# Extension: davidanson.vscode-markdownlint

# Disable only the rules that interfere with practical markdown writing
MD013: false  # Line length (inappropriate for markdown)
MD024: false  # Allow duplicate headings (helpful for consistent section patterns)
MD025: false  # Allow multiple H1 headings (front matter title + body H1 for LLM comprehension)
MD033: false  # Allow inline HTML (<details>, <tags>, etc.)
MD036: false  # Allow emphasis (bold/italic) without treating it as heading
MD040: false  # Fenced code blocks don't need language specified
MD035: false  # Horizontal rule style (scraped docs may use *** instead of ---)
MD041: false  # First line doesn't need to be h1
MD059: false  # Link text doesn't need to be descriptive (scraped docs have generic links)
MD060: false  # Table column style (scraped docs may use compact pipe formatting)
